languages:
  JavaScript: true
  PHP: true

exclude_paths:
- "system/**"
- "application/cms_bridge.php"
- "tests/**"
- "hooks/**"
- "application/libraries/elfinder/**"
- "js/**"
- "application/modules/translator/assets/js/**"
- "application/modules/admin_menu/menus/**"
- "generated-classes/Base/**"
- "generated-classes/Map/**"
- "Models/Base/**"
- "Models/Map/**"
- "application/third_party/**"