# This is a sample .codeclimate.yml configured for Engine analysis on Code
# Climate Platform. For an overview of the Code Climate Platform, see here:
# http://docs.codeclimate.com/article/300-the-codeclimate-platform

# Under the engines key, you can configure which engines will analyze your repo.
# Each key is an engine name. For each value, you need to specify enabled: true
# to enable the engine as well as any other engines-specific configuration.

# For more details, see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform

# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

engines:
# to turn on an engine, add it here and set enabled to `true`
# to turn off an engine, set enabled to `false` or remove it
  eslint:
    enabled: true
  csslint:
    enabled: true

# Engines can analyze files and report issues on them, but you can separately
# decide which files will receive ratings based on those issues. This is
# specified by path patterns under the ratings key.

# For more details see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform

# ratings:
#   paths:
#   - app/**
#   - lib/**
#   - "**.rb"
#   - "**.go"

# You can globally exclude files from being analyzed by any engine using the
# exclude_paths key.

exclude_paths:
- "system/**"
#- "application/cms_bridge.php"
#- "tests/**"
#- "**/tests/**"
#- "hooks/**"
#- "application/libraries/elfinder/**"
#- "js/**"
#- "application/modules/translator/assets/js/**"
#- "application/modules/admin_menu/menus/**"
#- "**/generated-classes/Base/**"
#- "**/generated-classes/Map/**"
#- "**/generated-classes/**/Base/**"
#- "**/generated-classes/**/Map/**"
#- "Models/Base/**"
#- "Models/Map/**"
#- "application/third_party/**"
#- "application/modules/banners/assets/js/cycle.js"
#- "templates/**"
#- "application/modules/egoods/assets/js/epub/**"
#- "application/modules/sitetest/**"
#- "application/modules/documentation/**"
#- "application/modules/my_module_frame/**"
#- "application/modules/egoods/assets/js/jwplayer/**"
#- "application/modules/egoods/vendors/**"
#- "application/modules/facebook_store/**"
#- "application/modules/gallery/assets/js/jquery.mousewheel-3.0.4.pack.js"
#- "application/modules/mod_stats/assets/js/nv.d3.js"
#- "application/modules/mod_stats/assets/js/d3.v3.js"
#- "application/modules/translate/**"
#- "application/modules/shop/obf/**"
#- "**/module_info.php"
#- "**/vendor/**"
#- "uploads_site/**"
