language: php
sudo: false
php:
    - 5.4
    - 5.5
matrix:
  allow_failures:
    - php: 5.5


install: composer install --dev
before_script: 
  - composer self-update
  #composer install
script: phpunit -c app/

