language: php

sudo: false


env:
  - DB=mysql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm


matrix:
  allow_failures:
  - php: 5.5
  
  
  before_install:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update
  
  before_script:
  - mkdir app/cache
  - chmod 777 app/cache
  - cp app/config/parameters.yml.desc app/config/parameters.yml
  - composer self-update




  

  

